first_product_link = "a.oe_product_image_link"
product_title = "h1[itemprop='name']"
not_available_text = "#add_to_cart_wrap .text-danger"
contact_us_btn = "text=Contact Us"
add_to_cart_btn = "#add_to_cart"
cart_quantity = ".my_cart_quantity"
terms_link = "a[href='/terms']"
terms_title = "h1"
continue_shopping_btn = "button.btn-secondary"
